---
functional:
  - Пользователь должен иметь возможность зарегистрироваться на сайте
  - Пользователь должен иметь возможность войти в систему, используя свое имя пользователя и пароль
  - Пользователь может создать игру с ботом 
  - Пользователь может создать игру с другим противником 
  - Пользователь может создать игру с другом
  - Пользователь может выбрать игру по уровню сложности
  - При создании игры пользователь может выбрать определенную игру или она будет подобрана наугад
  - Задачи должны быть даны на двух языках — русском и английском
  - У играков должна быть возможность менять язык программирования во время решения задач
  - У играков, во время решения задач, должна быть возможность видеть у друг друга редактор с кодом, вывод тестов
  - У других пользователей должна быть возможность следить за ходом игры
  - В игре должен быть чат, в котором общаются зарегистрированные пользователи
  - Завершенная игра должна быть доступна в записи
  - Пользователи должны получать очки, на основе которых будет строится рейтинг за неделю, месяц и за все время
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
implicit:
  - Локализация сайта
  -  






